### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ianlucas** [ianlucas/cslib#3]
- [x] Use `0` instead of `null` for `CS_InventoryItem.stickerswear` and `CS_inventoryItem.stickers`, make them `number[]`.
- [x] Have `CS_Inventory` constructor to accept a single argument for options.
- [x] Add Storage Units for `CS_Inventory`, default limit of 32 items.
- [x] Add `updatedat` to `CS_InventoryItem`, when a item is created its value is `(FIXED_TIMESTAMP - Date.now()) / 1000`.
- [x] Separated asset data JSON file for weapons and paints using legacy model.

**Comment by ianlucas** [comment]
- [ ] Separated asset data JSON file for weapons and paints using legacy model.
- [ ] Optimized static items for use with TypeScript. (Avoid repetition as much as possible).
- [ ] Optimized translation files.
